language: cpp

sudo: false   # Use the new container infrastructure

compiler:
  - clang
  - gcc

before_script:
  - cmake -DWITH_TESTS=1 -DWITH_EXAMPLE=1 .

script: 
  - cmake --build .
  - python run_tests
