language: cpp

sudo: false   # Use the new container infrastructure

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - clang-3.5
    - clang-3.6
    - clang-3.7
    - clang-3.8

before_script:
  - cmake -DWITH_TESTS=1 -DWITH_EXAMPLE=1 .

script: 
  - cmake --build .
  - python run_tests
